# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aclock < Formula
  desc "A simple clock for the terminal."
  homepage "https://github.com/yoshihicode/aclock"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoshihicode/aclock/releases/download/v0.0.4/aclock_darwin_amd64.tar.gz"
      sha256 "f33b88a0af7ba7fee61340356f84336fe524adaf997271d618c45b6f109f5eca"

      define_method(:install) do
        bin.install "aclock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoshihicode/aclock/releases/download/v0.0.4/aclock_darwin_arm64.tar.gz"
      sha256 "eb28a9202f20ff0d5fcde988a5029247619ad28f3d484bebd67cb32e435aa764"

      define_method(:install) do
        bin.install "aclock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshihicode/aclock/releases/download/v0.0.4/aclock_linux_amd64.tar.gz"
      sha256 "8eb63c279367f1e04fe9f685f38f7c1ef880b9a140c52d336e434d076fdf6c02"
      define_method(:install) do
        bin.install "aclock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshihicode/aclock/releases/download/v0.0.4/aclock_linux_arm64.tar.gz"
      sha256 "f12a086a2c15449ea7d4601febc85613d62b2c67848b5a33c2a0c22f63bdb43c"
      define_method(:install) do
        bin.install "aclock"
      end
    end
  end

  test do
    system "#{bin}/aclock --help"
  end
end
