# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Candle < Formula
  desc "candle is a joke command that displays a candle-like fire effect in your terminal."
  homepage "https://github.com/yoshihicode/candle"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoshihicode/candle/releases/download/v1.3.2/candle_darwin_amd64.tar.gz"
      sha256 "9a3375b52b50306edaf1005ddf025fe8e8560b3cb4437cd5f062e19bbb771c14"

      define_method(:install) do
        bin.install "candle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoshihicode/candle/releases/download/v1.3.2/candle_darwin_arm64.tar.gz"
      sha256 "9083a8985ed866092dc3ae70d1fd40652ad7d1760db9a0b86b4153bc6a9a9b3d"

      define_method(:install) do
        bin.install "candle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshihicode/candle/releases/download/v1.3.2/candle_linux_amd64.tar.gz"
      sha256 "10bf8a80462084724c693618e47c5c220f6662a5201793fd4e5539534661359d"
      define_method(:install) do
        bin.install "candle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshihicode/candle/releases/download/v1.3.2/candle_linux_arm64.tar.gz"
      sha256 "b830ab226eba08f25bedab39ccbf8601b8cd5d9c499358f2887accc1c778b889"
      define_method(:install) do
        bin.install "candle"
      end
    end
  end

  test do
    system "#{bin}/candle --help"
  end
end
