# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cubectl < Formula
  desc "cubectl controls cube instead of Kubernetes clusters."
  homepage "https://github.com/yoshihicode/cubectl"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoshihicode/cubectl/releases/download/v0.1.4/cubectl_darwin_amd64.tar.gz"
      sha256 "73e453effaf0e3f8f24cf800b127fc6cb939f831794867f7eb3647848c19a873"

      define_method(:install) do
        bin.install "cubectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoshihicode/cubectl/releases/download/v0.1.4/cubectl_darwin_arm64.tar.gz"
      sha256 "85ab2ca8a1d7c31ff332bcf2ee66399561b3b20dec554de868807987492f4cae"

      define_method(:install) do
        bin.install "cubectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshihicode/cubectl/releases/download/v0.1.4/cubectl_linux_amd64.tar.gz"
      sha256 "89a5419b0633911d2648a44d4c3c807e196d36b2178e20b1c14b8c0b63b2be29"
      define_method(:install) do
        bin.install "cubectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshihicode/cubectl/releases/download/v0.1.4/cubectl_linux_arm64.tar.gz"
      sha256 "11e35d78f5744c261b209881fbf9c78f53397f3fd382edd54dd042a7b1ebebac"
      define_method(:install) do
        bin.install "cubectl"
      end
    end
  end

  test do
    system "#{bin}/cubectl --help"
  end
end
