# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cubectl < Formula
  desc "cubectl controls cube instead of Kubernetes clusters."
  homepage "https://github.com/y-hatano-github/cubectl"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/y-hatano-github/cubectl/releases/download/v0.0.12/cubectl_darwin_amd64.tar.gz"
      sha256 "e8d4cb27982cc33dc49c4c65e0728db08d457d33b3e36d882f95bf2db0090ee7"

      def install
        bin.install "cubectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/y-hatano-github/cubectl/releases/download/v0.0.12/cubectl_darwin_arm64.tar.gz"
      sha256 "6fb861525d55b6449fe45a095529714d4d8e9ecaefbc9446beee34cf34558f1e"

      def install
        bin.install "cubectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/y-hatano-github/cubectl/releases/download/v0.0.12/cubectl_linux_amd64.tar.gz"
      sha256 "1b188d8d478ea4f0a93aaadffd45d39cc03b66e19311bdeff164c47f9752218d"
      def install
        bin.install "cubectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/y-hatano-github/cubectl/releases/download/v0.0.12/cubectl_linux_arm64.tar.gz"
      sha256 "09bb747d23e88724fb8bf568a291917d8daf085e0d86197947814898f24900fc"
      def install
        bin.install "cubectl"
      end
    end
  end

  test do
    system "#{bin}/cubectl --help"
  end
end
