# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cubectl < Formula
  desc "cubectl controls cube instead of Kubernetes clusters."
  homepage "https://github.com/yoshihicode/cubectl"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoshihicode/candle/releases/download/v1.3.0/candle_darwin_amd64.tar.gz"
      sha256 "dec9d9ba90a1b53433ff603584f51a87d967baadb1888d167c80ccfd06a3525e"

      define_method(:install) do
        bin.install "candle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoshihicode/candle/releases/download/v1.3.0/candle_darwin_arm64.tar.gz"
      sha256 "3a026375d2fcfdeb261dd6d82fd395369c954851573938efd2e8d402cb0fc73d"

      define_method(:install) do
        bin.install "candle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshihicode/candle/releases/download/v1.3.0/candle_linux_amd64.tar.gz"
      sha256 "00d5c291752aa68933b90d7a0e482a100af69550d6f6e4dd4b7e4d60b65891ae"
      define_method(:install) do
        bin.install "candle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshihicode/candle/releases/download/v1.3.0/candle_linux_arm64.tar.gz"
      sha256 "2e5f6d39e4e3efed0293ac949fab89c393d01c5548d9af178406172cfa82f985"
      define_method(:install) do
        bin.install "candle"
      end
    end
  end

  test do
    system "#{bin}/candle --help"
  end
end
