# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoPuyo < Formula
  desc "Go-Puyo is terminal based 'Puyo Puyo' similar game written in Go language."
  homepage "https://github.com/yoshihicode/go-puyo"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoshihicode/go-puyo/releases/download/v0.4.2/go-puyo_darwin_amd64.tar.gz"
      sha256 "2504f0ecd8ae1399da181c8a5daaafb766cfbf6eb601842b6491ffc9584fd948"

      define_method(:install) do
        bin.install "go-puyo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoshihicode/go-puyo/releases/download/v0.4.2/go-puyo_darwin_arm64.tar.gz"
      sha256 "d447e22aa10d8abe88ee61f67d94b4cef49a5ca10b6f40b3382e7602d0dc37d5"

      define_method(:install) do
        bin.install "go-puyo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshihicode/go-puyo/releases/download/v0.4.2/go-puyo_linux_amd64.tar.gz"
      sha256 "73889cb65ca73a3c48cd7a5e1ca7d986ecb418af408519a086a990292ccf1fbd"
      define_method(:install) do
        bin.install "go-puyo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshihicode/go-puyo/releases/download/v0.4.2/go-puyo_linux_arm64.tar.gz"
      sha256 "7dc1f2a8be96359c177f3fb9b4887fff06ca1632d7a1262d9e03a68e2f01446b"
      define_method(:install) do
        bin.install "go-puyo"
      end
    end
  end

  test do
    system "#{bin}/go-puyo --help"
  end
end
