# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maze3d < Formula
  desc "Maze 3D is a terminal-based 3D maze game written in Go."
  homepage "https://github.com/yoshihicode/maze3d"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/yoshihicode/maze3d/releases/download/v0.0.1/maze3d_darwin_amd64.tar.gz"
      sha256 "1bc0e59241e86cd0c00f422607533626b8cf74cddc19cdf0de3532a749cb0fb3"

      def install
        bin.install "maze3d"
      end
    end
    on_arm do
      url "https://github.com/yoshihicode/maze3d/releases/download/v0.0.1/maze3d_darwin_arm64.tar.gz"
      sha256 "6bc55ceae330765e14a7daccf5f2a62a9d69453f853ed6627c662f597d9f3c7e"

      def install
        bin.install "maze3d"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yoshihicode/maze3d/releases/download/v0.0.1/maze3d_linux_amd64.tar.gz"
        sha256 "1728587a9797dd425df792b0fc7452039481ba94fe0d2c16a14057d23dd22629"

        def install
          bin.install "maze3d"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yoshihicode/maze3d/releases/download/v0.0.1/maze3d_linux_arm64.tar.gz"
        sha256 "06ddf44fea30976d771ca37ba30b4bf19c256d0eaa35288622d269fdf8469d51"

        def install
          bin.install "maze3d"
        end
      end
    end
  end

  test do
    system "#{bin}/maze3d --help"
  end
end
