# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myt < Formula
  desc "myt is terminal based MySQL client."
  homepage "https://github.com/yoshihicode/myt"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoshihicode/myt/releases/download/v0.0.3/myt_darwin_amd64.tar.gz"
      sha256 "4bafb34f2e13879339f950a9816ca157629533a2c734b7a6f46582dcbf3e60d8"

      define_method(:install) do
        bin.install "myt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoshihicode/myt/releases/download/v0.0.3/myt_darwin_arm64.tar.gz"
      sha256 "df41ae473a1dc8dd03e3a5ddb8ec4bcb452ee0e796897cf2fd1774470a122d46"

      define_method(:install) do
        bin.install "myt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshihicode/myt/releases/download/v0.0.3/myt_linux_amd64.tar.gz"
      sha256 "72745ca0027ea7d251f08c42be677a31d5a1090b534fe6e9374939d2d5892b37"
      define_method(:install) do
        bin.install "myt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoshihicode/myt/releases/download/v0.0.3/myt_linux_arm64.tar.gz"
      sha256 "303f3fceb9fcd60647e0f5a8568afe0201bd35cac6066023ca04c2d951d33af8"
      define_method(:install) do
        bin.install "myt"
      end
    end
  end

  test do
    system "#{bin}/myt --help"
  end
end
